/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesIndexRouteImport } from './routes/rules/index'
import { Route as ReferencesIndexRouteImport } from './routes/references/index'
import { Route as RulesCategoryRouteImport } from './routes/rules/$category'
import { Route as ReferencesSlugRouteImport } from './routes/references/$slug'

const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesIndexRoute = ReferencesIndexRouteImport.update({
  id: '/references/',
  path: '/references/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesCategoryRoute = RulesCategoryRouteImport.update({
  id: '/rules/$category',
  path: '/rules/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesSlugRoute = ReferencesSlugRouteImport.update({
  id: '/references/$slug',
  path: '/references/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protocol': typeof ProtocolRoute
  '/references/$slug': typeof ReferencesSlugRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/references/': typeof ReferencesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protocol': typeof ProtocolRoute
  '/references/$slug': typeof ReferencesSlugRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/references': typeof ReferencesIndexRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protocol': typeof ProtocolRoute
  '/references/$slug': typeof ReferencesSlugRoute
  '/rules/$category': typeof RulesCategoryRoute
  '/references/': typeof ReferencesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protocol'
    | '/references/$slug'
    | '/rules/$category'
    | '/references/'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/protocol'
    | '/references/$slug'
    | '/rules/$category'
    | '/references'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/protocol'
    | '/references/$slug'
    | '/rules/$category'
    | '/references/'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtocolRoute: typeof ProtocolRoute
  ReferencesSlugRoute: typeof ReferencesSlugRoute
  RulesCategoryRoute: typeof RulesCategoryRoute
  ReferencesIndexRoute: typeof ReferencesIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/': {
      id: '/references/'
      path: '/references'
      fullPath: '/references/'
      preLoaderRoute: typeof ReferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$category': {
      id: '/rules/$category'
      path: '/rules/$category'
      fullPath: '/rules/$category'
      preLoaderRoute: typeof RulesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/$slug': {
      id: '/references/$slug'
      path: '/references/$slug'
      fullPath: '/references/$slug'
      preLoaderRoute: typeof ReferencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtocolRoute: ProtocolRoute,
  ReferencesSlugRoute: ReferencesSlugRoute,
  RulesCategoryRoute: RulesCategoryRoute,
  ReferencesIndexRoute: ReferencesIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
