/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as LogsImport } from './routes/logs'
import { Route as IndexImport } from './routes/index'
import { Route as AppsStackNameImport } from './routes/apps.$stackName'

const LogsRoute = LogsImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppsStackNameRoute = AppsStackNameImport.update({
  id: '/apps/$stackName',
  path: '/apps/$stackName',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/apps/$stackName': typeof AppsStackNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/apps/$stackName': typeof AppsStackNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/apps/$stackName': typeof AppsStackNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/apps/$stackName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs' | '/apps/$stackName'
  id: '__root__' | '/' | '/logs' | '/apps/$stackName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  AppsStackNameRoute: typeof AppsStackNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  AppsStackNameRoute: AppsStackNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
